### ISSUE TITLE
Add Phone Authentication to NativeScript App

### ISSUE THREAD

**Issue by naxmefy** [naxmefy/books#2]
**Prerequistes**

- [ ] Firebase Support enabled - #1 resolved

**Tasks**

- [ ] Activate Phone Authentication in Firebase Console
- [ ] Add UI (Login / Register Form)
- [ ] Add Logic to Login / Register
