### ISSUE TITLE
Add Email Authentication to NativeScript App

### ISSUE THREAD

**Issue by naxmefy** [naxmefy/books#6]
**Prerequistes**

- [ ] Firebase Support enabled - #1 resolved

**Tasks**

- [ ] Activate Email Authentication in Firebase Console
- [ ] Add UI (Login / Register Form)
- [ ] Add Logic to Login / Register
